project:
  type: book
  output-dir: docs

book:
  title: "Vozes e Visões: A Busca por um Sentido"
  subtitle: "Perspectivas Fenomenológicas, Culturais e Neurocientíficas"
  author:
    - name: "Henrique Alvarenga da Silva"
      affiliation: "Universidade Federal de São João del-Rei (UFSJ)"
      email: "henriquealvarenga@ufsj.edu.br"
      orcid: "0000-0001-9799-5240"
  date: "2025-12-20"
  date-format: "long"
  language: pt
  
  page-navigation: true
  search: true
  repo-url: https://github.com/henriquealvarenga/alucinacoes
  repo-actions: none
  
  sidebar:
    style: docked
    background: light
    collapse-level: 1
  
  chapters:
    - index.qmd
    - 00-introducao.qmd

    - part: "Parte I — A Busca por um Sentido"
      chapters:
        - 01-01-background-filosofico.qmd
        - 01-02-background-antropologico.qmd
        - 01-03-experiencia-intima.qmd
        - 01-04-experiencia-compartilhada.qmd
    
    - part: "Parte II — O sagrado"
      chapters:
        - 02-01-grecia-apolinea.qmd
        - 02-02-vozes-profeticas.qmd
        - 02-03-visoes-marianas.qmd
        - 02-04-discretio-spirituum.qmd
        - 02-05-xamanismo.qmd
    
    - part: "Parte III — O Cotidiano"
      chapters:
        - 03-01-fenomenologia.qmd
        - 03-02-continuum.qmd
        - 03-03-special-cases.qmd
        - 03-04-dimensoes.qmd
    
    
    - part: "Parte IV — A Ciência"
      chapters:
        - 04-01-historia-conceito.qmd
        - 04-02-neurobiologia.qmd
        - 04-03-substancias.qmd
        - 04-04-escalas.qmd
        - 04-05-ouvidores-vozes.qmd
    
    - references.qmd

# Bibliografia global
bibliography: references/references.bib
csl: references/csl_styles/ABNT.csl

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    mainfont: "Crimson Pro"
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 2
    code-fold: true
    lang: pt-BR

editor: visual

execute:
  freeze: auto