project:
  type: book
  output-dir: docs

book:
  title: "Alucinações, Vozes e Visões"
  subtitle: "Uma Breve Introdução"
  author: "Henrique Alvarenga da Silva"
  date: "2025-12-20"
  date-format: "long"
  language: pt
  
  chapters:
    - index.qmd
    - 01-introducao.qmd
    - 02-vozes-ou-alucinacoes.qmd
    - 03-vozes-populacao.qmd
    - 04-ouvi-uma-voz.qmd
    - 05-vozes-religiosidade.qmd
    - 06-vozes-revelacoes.qmd
    - 07-discretio-spiritum.qmd
    - 08-vozes-guerras.qmd
    - 09-visoes-culturais.qmd
    - 10-dimensoes-experiencia.qmd
    - 11-movimento-ouvidores.qmd
    - 12-alucinacoes-clinicas.qmd
    - references.qmd

  page-navigation: true
  search: true
  repo-url: https://github.com/henriquealvarenga/alucinacoes
  repo-actions: [edit, issue]
  
  sidebar:
    style: docked
    background: light
    collapse-level: 1


# Bibliografia global
bibliography: references/references.bib
csl: references/csl_styles/ABNT.csl  


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 2
    code-fold: true
    lang: pt-BR

editor: visual

execute:
  freeze: auto
